/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculatrice.IHM;

/**
 *
 * @author Thierry
 */
public class Calculatrice extends javax.swing.JFrame {

    // Déclaration des variables
    // Contient le résultat du calcul
    private double calcul = 0;
    // Chiffre saisie
    private String chiffre = "";
    // Gestion du point 
    private boolean mettrePoint = true;
    // Contient le signe de l'opérateur
    private String operation = "";
    
    // Concaténation des chiffre
    private void concateneChiffre(int nb){
        // Concaténation des chiffres passés en paramètre
        chiffre += nb;
        // Affichage à l'écran du chiffre
        LIB_Ecran.setText(chiffre);
    }
    
    // Méthode de calcul
    private void calculer(String operateur){
        // Si l'opérateur est vide
        if(operation.equals("")){
            // On affecte à opération l'opérateur passer en paramètre
            operation = operateur;
            // On affecte à calcul le chiffre contenu dans l'écran d'affichage
            calcul = Double.valueOf(LIB_Ecran.getText());
            // On affecte vide à chiffre qui va contenir un autre chiffre
            chiffre = "";
            // On met "mettrePoint" à vrai afin de pouvoir saisir le prochain nb avec une décimale
            mettrePoint = true;
        } else {
            // On appelle la méthode de calcul
            afficheResultat(operation);
            operation = operateur;
        }
        
    }
    
    // Affiche le résultat d'une opération
    private void afficheResultat(String operateur){
        switch(operateur){
            case "+" :
                calcul += Double.valueOf(LIB_Ecran.getText());
                LIB_Ecran.setText(""+calcul);
                break;
            case "-" :
                calcul -= Double.valueOf(LIB_Ecran.getText());
                LIB_Ecran.setText(""+calcul);
                break;
            case "*" :
                calcul *= Double.valueOf(LIB_Ecran.getText());
                LIB_Ecran.setText(""+calcul);
                break;
            case "/" :
                calcul /= Double.valueOf(LIB_Ecran.getText());
                LIB_Ecran.setText(""+calcul);
                break;
        }
        
        chiffre = "";
        mettrePoint = true;
    }
    
    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LIB_Ecran = new javax.swing.JLabel();
        BTN_Egal = new javax.swing.JButton();
        BTN_4 = new javax.swing.JButton();
        BTN_3 = new javax.swing.JButton();
        BTN_2 = new javax.swing.JButton();
        BTN_Multiplier = new javax.swing.JButton();
        BTN_5 = new javax.swing.JButton();
        BTN_6 = new javax.swing.JButton();
        BTN_Point = new javax.swing.JButton();
        BTN_1 = new javax.swing.JButton();
        BTN_8 = new javax.swing.JButton();
        BTN_9 = new javax.swing.JButton();
        BTN_Soustraire = new javax.swing.JButton();
        BTN_7 = new javax.swing.JButton();
        BTN_Clear = new javax.swing.JButton();
        BTN_Diviser = new javax.swing.JButton();
        BTN_PlusMoins = new javax.swing.JButton();
        BTN_0 = new javax.swing.JButton();
        BTN_Additionner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculatrice V2");
        setResizable(false);

        LIB_Ecran.setBackground(new java.awt.Color(255, 255, 255));
        LIB_Ecran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LIB_Ecran.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LIB_Ecran.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        LIB_Ecran.setEnabled(false);

        BTN_Egal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTN_Egal.setText("=");
        BTN_Egal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EgalActionPerformed(evt);
            }
        });

        BTN_4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_4.setText("4");
        BTN_4.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_4ActionPerformed(evt);
            }
        });

        BTN_3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_3.setText("3");
        BTN_3.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_3ActionPerformed(evt);
            }
        });

        BTN_2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_2.setText("2");
        BTN_2.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_2ActionPerformed(evt);
            }
        });

        BTN_Multiplier.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Multiplier.setText("*");
        BTN_Multiplier.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Multiplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MultiplierActionPerformed(evt);
            }
        });

        BTN_5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_5.setText("5");
        BTN_5.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_5ActionPerformed(evt);
            }
        });

        BTN_6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_6.setText("6");
        BTN_6.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_6ActionPerformed(evt);
            }
        });

        BTN_Point.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Point.setText(".");
        BTN_Point.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PointActionPerformed(evt);
            }
        });

        BTN_1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_1.setText("1");
        BTN_1.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_1ActionPerformed(evt);
            }
        });

        BTN_8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_8.setText("8");
        BTN_8.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_8ActionPerformed(evt);
            }
        });

        BTN_9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_9.setText("9");
        BTN_9.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_9ActionPerformed(evt);
            }
        });

        BTN_Soustraire.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Soustraire.setText("-");
        BTN_Soustraire.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Soustraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SoustraireActionPerformed(evt);
            }
        });

        BTN_7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_7.setText("7");
        BTN_7.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_7ActionPerformed(evt);
            }
        });

        BTN_Clear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Clear.setText("C");
        BTN_Clear.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ClearActionPerformed(evt);
            }
        });

        BTN_Diviser.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Diviser.setText("/");
        BTN_Diviser.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Diviser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DiviserActionPerformed(evt);
            }
        });

        BTN_PlusMoins.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_PlusMoins.setText("+/-");
        BTN_PlusMoins.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_PlusMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PlusMoinsActionPerformed(evt);
            }
        });

        BTN_0.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_0.setText("0");
        BTN_0.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_0ActionPerformed(evt);
            }
        });

        BTN_Additionner.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BTN_Additionner.setText("+");
        BTN_Additionner.setPreferredSize(new java.awt.Dimension(73, 73));
        BTN_Additionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AdditionnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LIB_Ecran, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_Egal, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN_PlusMoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_0, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_Additionner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTN_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTN_Soustraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BTN_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTN_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTN_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTN_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTN_Multiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BTN_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTN_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTN_Diviser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_Point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(LIB_Ecran, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN_2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_Diviser, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Multiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Soustraire, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_PlusMoins, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Additionner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_Egal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Traitement du bouton multiplier
    private void BTN_MultiplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MultiplierActionPerformed
        calculer("*");
    }//GEN-LAST:event_BTN_MultiplierActionPerformed
    
    // Traitement du bouton 2
    private void BTN_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_2ActionPerformed
        concateneChiffre(2);
    }//GEN-LAST:event_BTN_2ActionPerformed
      
    // Traitement du bouton 4
    private void BTN_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_4ActionPerformed
        concateneChiffre(4);
    }//GEN-LAST:event_BTN_4ActionPerformed

    // Traitement du bouton 5
    private void BTN_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_5ActionPerformed
        concateneChiffre(5);
    }//GEN-LAST:event_BTN_5ActionPerformed
//test GIHUB
    // Traitement du bouton point
    private void BTN_PointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PointActionPerformed
        if (mettrePoint == true){
            if(chiffre.equals("")) {
                chiffre = "0";
            }
            chiffre+=".";
            LIB_Ecran.setText(chiffre);
            mettrePoint = false;
        }
    }//GEN-LAST:event_BTN_PointActionPerformed

    // Traitement du bouton 1
    private void BTN_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_1ActionPerformed
        concateneChiffre(1);
    }//GEN-LAST:event_BTN_1ActionPerformed

    // Traitement du bouton 8
    private void BTN_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_8ActionPerformed
        concateneChiffre(8);
    }//GEN-LAST:event_BTN_8ActionPerformed

    // Traitement du bouton soustraire
    private void BTN_SoustraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SoustraireActionPerformed
        calculer("-");
    }//GEN-LAST:event_BTN_SoustraireActionPerformed

    // Traitement du bouton 7
    private void BTN_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_7ActionPerformed
        concateneChiffre(7);
    }//GEN-LAST:event_BTN_7ActionPerformed

    // Traitement du bouton clear
    private void BTN_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ClearActionPerformed
        mettrePoint = true;
        LIB_Ecran.setText("0");
        chiffre = "";
        calcul = 0;
        operation = "";
    }//GEN-LAST:event_BTN_ClearActionPerformed

    // Traitement du bouton diviser
    private void BTN_DiviserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DiviserActionPerformed
         calculer("/");
    }//GEN-LAST:event_BTN_DiviserActionPerformed

    // Traitement du bouton plusMoins
    private void BTN_PlusMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PlusMoinsActionPerformed
        if(chiffre.equals("")) {
                chiffre = ""+calcul;
        }
        double signe = Double.valueOf(chiffre) * (-1);
        chiffre = "" + signe;
        LIB_Ecran.setText(chiffre);
    }//GEN-LAST:event_BTN_PlusMoinsActionPerformed

    // Traitement du bouton 0
    private void BTN_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_0ActionPerformed
        if (!chiffre.equals("")){
            concateneChiffre(0);
        }
    }//GEN-LAST:event_BTN_0ActionPerformed

    // Traitement du bouton additionner
    private void BTN_AdditionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AdditionnerActionPerformed
         calculer("+");
    }//GEN-LAST:event_BTN_AdditionnerActionPerformed

    // Traitement du bouton 9
    private void BTN_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_9ActionPerformed
        concateneChiffre(9);
    }//GEN-LAST:event_BTN_9ActionPerformed

    // Traitement du bouton 6
    private void BTN_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_6ActionPerformed
        concateneChiffre(6);
    }//GEN-LAST:event_BTN_6ActionPerformed
    
    // Traitement du bouton 3
    private void BTN_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_3ActionPerformed
        concateneChiffre(3);
    }//GEN-LAST:event_BTN_3ActionPerformed

    // Traitement du bouton égal
    private void BTN_EgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EgalActionPerformed
        afficheResultat(operation);
        LIB_Ecran.setText(""+calcul);
        operation ="";
    }//GEN-LAST:event_BTN_EgalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_0;
    private javax.swing.JButton BTN_1;
    private javax.swing.JButton BTN_2;
    private javax.swing.JButton BTN_3;
    private javax.swing.JButton BTN_4;
    private javax.swing.JButton BTN_5;
    private javax.swing.JButton BTN_6;
    private javax.swing.JButton BTN_7;
    private javax.swing.JButton BTN_8;
    private javax.swing.JButton BTN_9;
    private javax.swing.JButton BTN_Additionner;
    private javax.swing.JButton BTN_Clear;
    private javax.swing.JButton BTN_Diviser;
    private javax.swing.JButton BTN_Egal;
    private javax.swing.JButton BTN_Multiplier;
    private javax.swing.JButton BTN_PlusMoins;
    private javax.swing.JButton BTN_Point;
    private javax.swing.JButton BTN_Soustraire;
    private javax.swing.JLabel LIB_Ecran;
    // End of variables declaration//GEN-END:variables
}
